on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get git branch name
        id: branch-name
        uses: tj-actions/branch-names@v8
      - id: create-branch
        uses: neondatabase/create-branch-action@v5
        with:
          username: "neondb_owner"
          api_key: ${{ secrets.NEON_API_KEY }}
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: preview/${{ steps.branch-name.outputs.current_branch }}
      - id: add-neon-env-wrangler
        run: |
          echo "[vars]" >> wrangler.toml
          echo "DATABASE_URL = \"${{ steps.create-branch.outputs.db_url_with_pooler }}\"" >> wrangler.toml
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install Project Dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Publish to CF Pages
        run: CLOUDFLARE_ACCOUNT_ID=b14076a63f14946d1240aa7d2642ad9f CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} npx wrangler@latest pages deploy --project-name="cloudflare-demo-3"
