on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get git branch name
        id: branch-name
        uses: tj-actions/branch-names@v8
      - id: create-branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          username: "neondb_owner"
          branch_name: preview/${{ steps.branch-name.outputs.current_branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install deps
        run: npm install
      - name: Run the build
        run: npm run build
      - name: Publish to Cloudflare Pages
        run: CLOUDFLARE_ACCOUNT_ID=b14076a63f14946d1240aa7d2642ad9f CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} npx wrangler@latest pages deploy ./dist --project-name="cloudflare-demo-3" --var DATABASE_URL:\"${{ steps.create-branch.outputs.db_url_with_pooler }}\"
